apiVersion: kustomize.k06.in/v1alpha1
kind: VaultSecretGenerator
metadata:
  name: vault-secret
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ../krm-vault-secret.sh
    # config.kubernetes.io/function: |
    #   exec:
    #     path: ./plugins/krm-vault-secret.sh
spec:
  - name: yourpass
    key: secret/pass
    field: passcode
  - name: youremail
    key: secret/addr
    field: email
